spring.application.name=demo-shops

spring.datasource.url=jdbc:mysql://localhost:3306/dream_shops_db
spring.datasource.username=root
spring.datasource.password=Kumar@123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

api.prefix=/api/v1
#why we are using the Dialect inside this.because we also define dependency so why here again we are assing?

# image upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

auth.token.expirationInMils=3600000
auth.token.jwtSecret=36763979244226452948404D635166546A576D5A71344743777217A25432A462D

